### ISSUE TITLE
resolution = config.resolve_build_setting(setting)

### ISSUE THREAD

**Issue by ramgopal-zopsmart** [yukiarrr/ios-build-action#105]
[14:58:15]: Error in your Fastfile at line 220
[14:58:15]:     218:	  # to continue expanding build settings and evaluate modifiers
[14:58:15]:     219:	  def resolve_recursive_build_setting(config, setting)
[14:58:15]:  => 220:	    resolution = config.resolve_build_setting(setting)
[14:58:15]:     221:	
[14:58:15]:     222:	    # finds values with one of

[14:58:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Fastfile:220:in `resolve_recursive_build_setting': \e[31m[!] undefined method `resolve_build_setting' for nil:NilClass\e[0m (NoMethodError)
	from Fastfile:132:in `block (3 levels) in parsing_binding'
	from Fastfile:122:in `each'
	from Fastfile:122:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:[157](https://github.com/zopping/ios-admin-app/actions/runs/4787827634/jobs/8513596406#step:5:158):in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
Fastfile:220:in `resolve_recursive_build_setting': undefined method `resolve_build_setting' for nil:NilClass (NoMethodError)
	from Fastfile:132:in `block (3 levels) in parsing_binding'
	from Fastfile:122:in `each'
	from Fastfile:122:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'

What might be the issue?

**Comment by JulesBer** [comment]
Hello can you share how you fixed this please ?
